---
title: "sobekio - Einleitung"
author: "Dinh Quang Duong, M2 B40"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
    fig_width: 9
    fig_height: 6
    fig_caption: true
    df_print: paged
    max.print: 10
    code_folding: hide
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sobekio)
library(data.table)
library(dplyr)
library(ggplot2)
library(stringr)
library(purrr)
```

# Einleitung

Das R-Package `sobekio` unterstützt SOBEK-Benutzer, um SOBEK `Input` zu vorbereiten und `Output` auszulesen. SOBEK bedeutet hier nur `SOBEK-RIVER Version 2` und `SOBEK RE`. `Input` sind `boundary.dat` und `lateral.dat`; `Output` sind `.HIS` Dateien. Zeitreihen für Boundary werden von R `data.table` zu SOBEK Zeitreihe-Format konvertiert. `Output` wird direkt von binary format ausgelesen. Außerdem gibt es Funktionen, mit der man Standard-Grafiks erstellen und Sobek-Projekt managen kann.

## SOBEK Projekt

Jedes SOBEK Projekt ist in einem Ordner eingerichtet. Wichtige Dateien in dem Ordner sind:

+ caselist.cmt: Liste alle `SOBEK-Case` mit deren `Case-Name` und `Case-Ordner`
+ FIXED: vordenifierte Tabelle, Karte und Werte
+ restart: Datein für `RESTART`
+ Nummerierte Ordners: Case-Ordner

## SOBEK Case

Ein SOBEK Projekt kann mehrere Cases haben, jede Case hat eigenen Ordner und Name. Case-Ordner und  Case-Name müssen unique sein.