# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read data from HIS file for time series and column given by mask
#'
#' @param path Path to HIS file
#' @param mask Indexes of columns to get data. Counting from 1.
#' The time column will be always included.
#' @param startTS Index of starting time step to read. Default read all
#' @param nTS Number of time steps to read. Default read all after and included the StartTS
#' @export
readHis <- function(path, mask, startTS = 1L, nTS = -1L, dt = 60L) {
    .Call(`_sobekio_readHis`, path, mask, startTS, nTS, dt)
}

